### ISSUE TITLE
stable versions of docs not getting generated

### ISSUE THREAD

**Issue by gaelforget** [JuliaOcean/PlanktonIndividuals.jl#51]
I believe this may have to do with the need to (re?)generate deploy keys & secret as explained in the documenter.jl docs @ https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions

(from https://juliadocs.github.io/Documenter.jl/stable/man/hosting/)

**Comment by zhenwu0728** [comment]
Thanks! @gaelforget Problem solved!
